<?php

namespace Proxy\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entity_Operation extends \DefaultDb_Entity_Operation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getShipment()
    {
        $this->__load();
        return parent::getShipment();
    }

    public function getRoute()
    {
        $this->__load();
        return parent::getRoute();
    }

    public function getOperationDate()
    {
        $this->__load();
        return parent::getOperationDate();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getCost()
    {
        $this->__load();
        return parent::getCost();
    }

    public function getCostoEnviador()
    {
        $this->__load();
        return parent::getCostoEnviador();
    }

    public function setShipment($shipment)
    {
        $this->__load();
        return parent::setShipment($shipment);
    }

    public function setRoute($route)
    {
        $this->__load();
        return parent::setRoute($route);
    }

    public function setOperationDate(\DateTime $operationDate)
    {
        $this->__load();
        return parent::setOperationDate($operationDate);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setCost($cost)
    {
        $this->__load();
        return parent::setCost($cost);
    }

    public function setCostoEnviador($costoEnviador)
    {
        $this->__load();
        return parent::setCostoEnviador($costoEnviador);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'operationDate', 'status', 'cost', 'costoEnviador', 'shipment', 'route');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}