<?php

namespace MasFletes\DefaultDb\Proxy\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entity_Shipment extends \DefaultDb_Entity_Shipment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCreation_date()
    {
        $this->__load();
        return parent::getCreation_date();
    }

    public function getVehicle()
    {
        $this->__load();
        return parent::getVehicle();
    }

    public function getVehicleType()
    {
        $this->__load();
        return parent::getVehicleType();
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function getStateOrigin()
    {
        $this->__load();
        return parent::getStateOrigin();
    }

    public function getStateDestiny()
    {
        $this->__load();
        return parent::getStateDestiny();
    }

    public function getMunicipalityOrigin()
    {
        $this->__load();
        return parent::getMunicipalityOrigin();
    }

    public function getMunicipalityDestiny()
    {
        $this->__load();
        return parent::getMunicipalityDestiny();
    }

    public function getFrequency()
    {
        $this->__load();
        return parent::getFrequency();
    }

    public function getShipmentAccepted()
    {
        $this->__load();
        return parent::getShipmentAccepted();
    }

    public function getEffectiveDays()
    {
        $this->__load();
        return parent::getEffectiveDays();
    }

    public function getContactName()
    {
        $this->__load();
        return parent::getContactName();
    }

    public function getContactPhone()
    {
        $this->__load();
        return parent::getContactPhone();
    }

    public function getSourceDate()
    {
        $this->__load();
        return parent::getSourceDate();
    }

    public function getSourceAddress()
    {
        $this->__load();
        return parent::getSourceAddress();
    }

    public function getDestinyDate()
    {
        $this->__load();
        return parent::getDestinyDate();
    }

    public function getDestinyAddress()
    {
        $this->__load();
        return parent::getDestinyAddress();
    }

    public function getShipmentType()
    {
        $this->__load();
        return parent::getShipmentType();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setComments($comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function setCreation_date(\DateTime $creation_date)
    {
        $this->__load();
        return parent::setCreation_date($creation_date);
    }

    public function setVehicle($vehicle)
    {
        $this->__load();
        return parent::setVehicle($vehicle);
    }

    public function setVehicleType($vehicleType)
    {
        $this->__load();
        return parent::setVehicleType($vehicleType);
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function setStateOrigin($stateOrigin)
    {
        $this->__load();
        return parent::setStateOrigin($stateOrigin);
    }

    public function setStateDestiny($stateDestiny)
    {
        $this->__load();
        return parent::setStateDestiny($stateDestiny);
    }

    public function setMunicipalityOrigin($municipalityOrigin)
    {
        $this->__load();
        return parent::setMunicipalityOrigin($municipalityOrigin);
    }

    public function setMunicipalityDestiny($municipalityDestiny)
    {
        $this->__load();
        return parent::setMunicipalityDestiny($municipalityDestiny);
    }

    public function setFrequency($frequency)
    {
        $this->__load();
        return parent::setFrequency($frequency);
    }

    public function setShipmentAccepted($shipmentAccepted)
    {
        $this->__load();
        return parent::setShipmentAccepted($shipmentAccepted);
    }

    public function setEffectiveDays($effectiveDays)
    {
        $this->__load();
        return parent::setEffectiveDays($effectiveDays);
    }

    public function setContactName($contactName)
    {
        $this->__load();
        return parent::setContactName($contactName);
    }

    public function setContactPhone($contactPhone)
    {
        $this->__load();
        return parent::setContactPhone($contactPhone);
    }

    public function setSourceDate(\DateTime $sourceDate)
    {
        $this->__load();
        return parent::setSourceDate($sourceDate);
    }

    public function setSourceAddress($sourceAddress)
    {
        $this->__load();
        return parent::setSourceAddress($sourceAddress);
    }

    public function setDestinyDate(\DateTime $destinyDate)
    {
        $this->__load();
        return parent::setDestinyDate($destinyDate);
    }

    public function setDestinyAddress($destinyAddress)
    {
        $this->__load();
        return parent::setDestinyAddress($destinyAddress);
    }

    public function setShipmentType($shipmentType)
    {
        $this->__load();
        return parent::setShipmentType($shipmentType);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creation_date', 'frequency', 'shipmentAccepted', 'effectiveDays', 'contactName', 'contactPhone', 'sourceDate', 'sourceAddress', 'destinyDate', 'destinyAddress', 'comments', 'vehicle', 'vehicleType', 'user', 'stateOrigin', 'stateDestiny', 'municipalityOrigin', 'municipalityDestiny', 'shipmentType');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}